com.code.generation.v1_3.exception.ManyDefinitionForSameCallableFoundException: function void func()
